### ISSUE TITLE
Component: Related Posts

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#21]
Displays up to a maximum of 2 related posts. Related posts are manually selected on a per-post basis and can be either Spotlights or Posts. Note that to accommodate an issue in Forestry, this should look at the related_spotlights and related_commentaries front matter field. There should only be 2 posts total displayed.

Each related post should show:
- [x] Post Title
- [x] Publish Date

The "View All" link should go to the collection archive page (eg. `/commentary/` for posts) and should only appear if there is related content. Implement the logic in `_includes/view-all-link.html` The view-all-link include should take the URL as a parameter so it can be reused in other places on the site.

![screen shot 2018-11-14 at 5 00 07 pm](https://user-images.githubusercontent.com/1896496/48515498-e2710f00-e82e-11e8-81aa-3838f68b1f82.png)

**Comment by aleesteele** [comment]
Just confirming what needs to be done for this, to tackle tomorrow.
- Break up `related-content` on forestry into two fields, one for spotlights, one for commentary. So the user can select either one of each, or both, or none at all. Does the order matter? 
- Following up on this, I had been wondering about the styles, and whether or not either spotlights are commentaries were going to be differentiated by color or a content-type label, etc. because of this change, kinda like the hover style samples that Tucker had integrated into some of the zeplin boards.
![screen shot 2018-12-04 at 3 48 54 pm](https://user-images.githubusercontent.com/18509789/49472989-d39ecc00-f7de-11e8-9064-359d6496f2ce.png)
I won't be doing anything about the second of course, was just wondering.

**Comment by jnschrag** [comment]
@aleesteele To reiterate our discussion in stand-up:

- This is correct. I would put the selector for the commentaries first and the spotlights second. When you merge the two arrays together to get the full list of items, you can then sort by date and use that to get the 2 most recent (in case more than 2 were selected by the user).
- As far as I'm aware, no commentary & spotlights will not be differentiated stylistically.
- When you're implementing these styles, keep in mind that the post title should use the `%post-block__title--related` placeholder.
- Also note that the post date & label do not use the same placeholders for typography as they do in other places on the site. They are slightly different.
